# Generated by Django 2.2.2 on 2019-06-16 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('ultimaReposicion', models.DateTimeField(verbose_name='Última Reposición')),
            ],
        ),
        migrations.CreateModel(
            name='WaffleIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'WaffleIndexes',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.PositiveIntegerField(default=0)),
                ('administrador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('valorTotal', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ManyToManyField(to='WaffleHouse.Cliente')),
                ('producto', models.ManyToManyField(to='WaffleHouse.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='IndexActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WaffleHouse.WaffleIndex')),
            ],
            options={
                'verbose_name_plural': 'IndexActual',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEntrada', models.CharField(max_length=5)),
                ('horaSalida', models.CharField(max_length=5)),
                ('diasTrabaja', models.CharField(max_length=20)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WaffleHouse.Trabajador')),
            ],
        ),
    ]
